//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBCP.ServiceSIGES.Aplication.WebServiceTienda {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceTienda.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Articulos_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Articulos_Consultar(int val_EmpresaId, string val_ArticuloId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Articulos_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Articulos_ConsultarAsync(int val_EmpresaId, string val_ArticuloId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Articulos_Caracteristicas_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Articulos_Caracteristicas_Consultar(int val_EmpresaId, int val_LocalId, string val_ArticuloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Articulos_Caracteristicas_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Articulos_Caracteristicas_ConsultarAsync(int val_EmpresaId, int val_LocalId, string val_ArticuloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Articulos_Alternativos_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Articulos_Alternativos_Consultar(int val_EmpresaId, string val_ArticuloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Articulos_Alternativos_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Articulos_Alternativos_ConsultarAsync(int val_EmpresaId, string val_ArticuloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insumos_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Insumos_Consultar(int val_EmpresaId, string val_ArticuloId, string val_InsumoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insumos_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Insumos_ConsultarAsync(int val_EmpresaId, string val_ArticuloId, string val_InsumoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldos_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Saldos_Consultar(string val_nrotarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldos_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Saldos_ConsultarAsync(string val_nrotarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_Tipo_Cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Consultar_Tipo_Cliente(string val_clienteid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_Tipo_Cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Consultar_Tipo_ClienteAsync(string val_clienteid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldos_Consultar_Contrato", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Saldos_Consultar_Contrato(string val_nrotarjeta, string val_nrocontrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldos_Consultar_Contrato", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Saldos_Consultar_ContratoAsync(string val_nrotarjeta, string val_nrocontrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Licitaciones_Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Saldo_Licitaciones_Actualizar(string val_local, string val_cliente, string val_nrocontrato, string val_nrotarjeta, string val_mtosoles, string val_cantidad, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Licitaciones_Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Licitaciones_ActualizarAsync(string val_local, string val_cliente, string val_nrocontrato, string val_nrotarjeta, string val_mtosoles, string val_cantidad, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Licitaciones_Anulacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Saldo_Licitaciones_Anulacion(string val_local, string val_cliente, string val_nrocontrato, string val_nrotarjeta, string val_mtosoles, string val_cantidad, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Licitaciones_Anulacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Licitaciones_AnulacionAsync(string val_local, string val_cliente, string val_nrocontrato, string val_nrotarjeta, string val_mtosoles, string val_cantidad, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Corporativo_Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Saldo_Corporativo_Actualizar(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Corporativo_Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Corporativo_ActualizarAsync(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Corporativo_Anulacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Saldo_Corporativo_Anulacion(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Corporativo_Anulacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Corporativo_AnulacionAsync(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Corporativo_Cobranza", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Saldo_Corporativo_Cobranza(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Corporativo_Cobranza", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Corporativo_CobranzaAsync(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Corporativo_Cobranza_Anulacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Saldo_Corporativo_Cobranza_Anulacion(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saldo_Corporativo_Cobranza_Anulacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Corporativo_Cobranza_AnulacionAsync(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PackVirtual_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PackVirtual_Consultar(int val_EmpresaId, string val_ArticuloId, string val_CdAmarre, string val_PromocionId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PackVirtual_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PackVirtual_ConsultarAsync(int val_EmpresaId, string val_ArticuloId, string val_CdAmarre, string val_PromocionId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Precio_Promo_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Precio_Promo_Consultar(int val_EmpresaId, string val_PromocionId, string val_ArticuloId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Precio_Promo_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Precio_Promo_ConsultarAsync(int val_EmpresaId, string val_PromocionId, string val_ArticuloId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Proveedores_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Proveedores_Consultar(int val_EmpresaId, string val_ProveedorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Proveedores_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Proveedores_ConsultarAsync(int val_EmpresaId, string val_ProveedorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Proveedore_Articulo_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Proveedore_Articulo_Consultar(int val_EmpresaId, string val_ProveedorId, string val_ArticuloId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Proveedore_Articulo_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Proveedore_Articulo_ConsultarAsync(int val_EmpresaId, string val_ProveedorId, string val_ArticuloId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Categorias_Consultar(string val_GrupoId01);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Categorias_ConsultarAsync(string val_GrupoId01);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Familias_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Familias_Consultar(string val_GrupoId02);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Familias_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Familias_ConsultarAsync(string val_GrupoId02);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubFamilias_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SubFamilias_Consultar(string val_GrupoId03);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubFamilias_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SubFamilias_ConsultarAsync(string val_GrupoId03);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UMedida_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable UMedida_Consultar(string val_UMedidaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UMedida_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> UMedida_ConsultarAsync(string val_UMedidaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Redondeo_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Redondeo_Consultar(string val_cat_nemonico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Redondeo_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Redondeo_ConsultarAsync(string val_cat_nemonico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Almacen_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Almacen_Consultar(int val_EmpresaId, int val_LocalId, int val_AlmacenId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Almacen_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Almacen_ConsultarAsync(int val_EmpresaId, int val_LocalId, int val_AlmacenId, int val_Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estado_Proceso_WebService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Estado_Proceso_WebService(int val_EmpresaId, int val_LocalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Estado_Proceso_WebService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Estado_Proceso_WebServiceAsync(int val_EmpresaId, int val_LocalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Orden_Compra_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Orden_Compra_Consultar(int val_EmpresaId, int val_LocalId, string val_NroPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Orden_Compra_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Orden_Compra_ConsultarAsync(int val_EmpresaId, int val_LocalId, string val_NroPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Orden_Compra_Detalle_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Orden_Compra_Detalle_Consultar(int val_EmpresaId, int val_LocalId, string val_NroPedido, int val_Item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Orden_Compra_Detalle_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Orden_Compra_Detalle_ConsultarAsync(int val_EmpresaId, int val_LocalId, string val_NroPedido, int val_Item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Consulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EasyTaxiCODESFile_Consulta(string val_value, string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento, string val_fecsistema, string val_hora, string val_cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_ConsultaAsync(string val_value, string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento, string val_fecsistema, string val_hora, string val_cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Consulta_Documento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EasyTaxiCODESFile_Consulta_Documento(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Consulta_Documento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_Consulta_DocumentoAsync(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Liberar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EasyTaxiCODESFile_Liberar(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Liberar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_LiberarAsync(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Anular", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EasyTaxiCODESFile_Anular(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Anular", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_AnularAsync(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Anexado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EasyTaxiCODESFile_Anexado(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento, string val_nroplaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EasyTaxiCODESFile_Anexado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_AnexadoAsync(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento, string val_nroplaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Clientes_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Clientes_Consultar(int val_EmpresaId, string val_ClienteId, int val_TipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Clientes_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Clientes_ConsultarAsync(int val_EmpresaId, string val_ClienteId, int val_TipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LineaCredito_SaldoClid_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LineaCredito_SaldoClid_Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LineaCredito_SaldoClid_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LineaCredito_SaldoClid_ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LineaCredito_SaldoClic_Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LineaCredito_SaldoClic_Consultar(int val_EmpresaId, int val_LocalId, string val_Cdcliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LineaCredito_SaldoClic_Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LineaCredito_SaldoClic_ConsultarAsync(int val_EmpresaId, int val_LocalId, string val_Cdcliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ITBCP.ServiceSIGES.Aplication.WebServiceTienda.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ITBCP.ServiceSIGES.Aplication.WebServiceTienda.Service1Soap>, ITBCP.ServiceSIGES.Aplication.WebServiceTienda.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Articulos_Consultar(int val_EmpresaId, string val_ArticuloId, int val_Tipo) {
            return base.Channel.Articulos_Consultar(val_EmpresaId, val_ArticuloId, val_Tipo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Articulos_ConsultarAsync(int val_EmpresaId, string val_ArticuloId, int val_Tipo) {
            return base.Channel.Articulos_ConsultarAsync(val_EmpresaId, val_ArticuloId, val_Tipo);
        }
        
        public System.Data.DataTable Articulos_Caracteristicas_Consultar(int val_EmpresaId, int val_LocalId, string val_ArticuloId) {
            return base.Channel.Articulos_Caracteristicas_Consultar(val_EmpresaId, val_LocalId, val_ArticuloId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Articulos_Caracteristicas_ConsultarAsync(int val_EmpresaId, int val_LocalId, string val_ArticuloId) {
            return base.Channel.Articulos_Caracteristicas_ConsultarAsync(val_EmpresaId, val_LocalId, val_ArticuloId);
        }
        
        public System.Data.DataTable Articulos_Alternativos_Consultar(int val_EmpresaId, string val_ArticuloId) {
            return base.Channel.Articulos_Alternativos_Consultar(val_EmpresaId, val_ArticuloId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Articulos_Alternativos_ConsultarAsync(int val_EmpresaId, string val_ArticuloId) {
            return base.Channel.Articulos_Alternativos_ConsultarAsync(val_EmpresaId, val_ArticuloId);
        }
        
        public System.Data.DataTable Insumos_Consultar(int val_EmpresaId, string val_ArticuloId, string val_InsumoId) {
            return base.Channel.Insumos_Consultar(val_EmpresaId, val_ArticuloId, val_InsumoId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Insumos_ConsultarAsync(int val_EmpresaId, string val_ArticuloId, string val_InsumoId) {
            return base.Channel.Insumos_ConsultarAsync(val_EmpresaId, val_ArticuloId, val_InsumoId);
        }
        
        public System.Data.DataTable Saldos_Consultar(string val_nrotarjeta) {
            return base.Channel.Saldos_Consultar(val_nrotarjeta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Saldos_ConsultarAsync(string val_nrotarjeta) {
            return base.Channel.Saldos_ConsultarAsync(val_nrotarjeta);
        }
        
        public System.Data.DataTable Consultar_Tipo_Cliente(string val_clienteid) {
            return base.Channel.Consultar_Tipo_Cliente(val_clienteid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Consultar_Tipo_ClienteAsync(string val_clienteid) {
            return base.Channel.Consultar_Tipo_ClienteAsync(val_clienteid);
        }
        
        public System.Data.DataTable Saldos_Consultar_Contrato(string val_nrotarjeta, string val_nrocontrato) {
            return base.Channel.Saldos_Consultar_Contrato(val_nrotarjeta, val_nrocontrato);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Saldos_Consultar_ContratoAsync(string val_nrotarjeta, string val_nrocontrato) {
            return base.Channel.Saldos_Consultar_ContratoAsync(val_nrotarjeta, val_nrocontrato);
        }
        
        public System.Data.DataTable Saldo_Licitaciones_Actualizar(string val_local, string val_cliente, string val_nrocontrato, string val_nrotarjeta, string val_mtosoles, string val_cantidad, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Licitaciones_Actualizar(val_local, val_cliente, val_nrocontrato, val_nrotarjeta, val_mtosoles, val_cantidad, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Licitaciones_ActualizarAsync(string val_local, string val_cliente, string val_nrocontrato, string val_nrotarjeta, string val_mtosoles, string val_cantidad, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Licitaciones_ActualizarAsync(val_local, val_cliente, val_nrocontrato, val_nrotarjeta, val_mtosoles, val_cantidad, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Data.DataTable Saldo_Licitaciones_Anulacion(string val_local, string val_cliente, string val_nrocontrato, string val_nrotarjeta, string val_mtosoles, string val_cantidad, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Licitaciones_Anulacion(val_local, val_cliente, val_nrocontrato, val_nrotarjeta, val_mtosoles, val_cantidad, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Licitaciones_AnulacionAsync(string val_local, string val_cliente, string val_nrocontrato, string val_nrotarjeta, string val_mtosoles, string val_cantidad, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Licitaciones_AnulacionAsync(val_local, val_cliente, val_nrocontrato, val_nrotarjeta, val_mtosoles, val_cantidad, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Data.DataTable Saldo_Corporativo_Actualizar(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Corporativo_Actualizar(val_local, val_cliente, val_nrotarjeta, val_mtosoles, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Corporativo_ActualizarAsync(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Corporativo_ActualizarAsync(val_local, val_cliente, val_nrotarjeta, val_mtosoles, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Data.DataTable Saldo_Corporativo_Anulacion(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Corporativo_Anulacion(val_local, val_cliente, val_nrotarjeta, val_mtosoles, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Corporativo_AnulacionAsync(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Corporativo_AnulacionAsync(val_local, val_cliente, val_nrotarjeta, val_mtosoles, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Data.DataTable Saldo_Corporativo_Cobranza(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Corporativo_Cobranza(val_local, val_cliente, val_nrotarjeta, val_mtosoles, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Corporativo_CobranzaAsync(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Corporativo_CobranzaAsync(val_local, val_cliente, val_nrotarjeta, val_mtosoles, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Data.DataTable Saldo_Corporativo_Cobranza_Anulacion(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Corporativo_Cobranza_Anulacion(val_local, val_cliente, val_nrotarjeta, val_mtosoles, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Saldo_Corporativo_Cobranza_AnulacionAsync(string val_local, string val_cliente, string val_nrotarjeta, string val_mtosoles, string val_seriemaq, string val_cdtipodoc, string val_nrodocumento, string val_mensaje) {
            return base.Channel.Saldo_Corporativo_Cobranza_AnulacionAsync(val_local, val_cliente, val_nrotarjeta, val_mtosoles, val_seriemaq, val_cdtipodoc, val_nrodocumento, val_mensaje);
        }
        
        public System.Data.DataTable PackVirtual_Consultar(int val_EmpresaId, string val_ArticuloId, string val_CdAmarre, string val_PromocionId, int val_Tipo) {
            return base.Channel.PackVirtual_Consultar(val_EmpresaId, val_ArticuloId, val_CdAmarre, val_PromocionId, val_Tipo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PackVirtual_ConsultarAsync(int val_EmpresaId, string val_ArticuloId, string val_CdAmarre, string val_PromocionId, int val_Tipo) {
            return base.Channel.PackVirtual_ConsultarAsync(val_EmpresaId, val_ArticuloId, val_CdAmarre, val_PromocionId, val_Tipo);
        }
        
        public System.Data.DataTable Precio_Promo_Consultar(int val_EmpresaId, string val_PromocionId, string val_ArticuloId, int val_Tipo) {
            return base.Channel.Precio_Promo_Consultar(val_EmpresaId, val_PromocionId, val_ArticuloId, val_Tipo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Precio_Promo_ConsultarAsync(int val_EmpresaId, string val_PromocionId, string val_ArticuloId, int val_Tipo) {
            return base.Channel.Precio_Promo_ConsultarAsync(val_EmpresaId, val_PromocionId, val_ArticuloId, val_Tipo);
        }
        
        public System.Data.DataTable Proveedores_Consultar(int val_EmpresaId, string val_ProveedorId) {
            return base.Channel.Proveedores_Consultar(val_EmpresaId, val_ProveedorId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Proveedores_ConsultarAsync(int val_EmpresaId, string val_ProveedorId) {
            return base.Channel.Proveedores_ConsultarAsync(val_EmpresaId, val_ProveedorId);
        }
        
        public System.Data.DataTable Proveedore_Articulo_Consultar(int val_EmpresaId, string val_ProveedorId, string val_ArticuloId, int val_Tipo) {
            return base.Channel.Proveedore_Articulo_Consultar(val_EmpresaId, val_ProveedorId, val_ArticuloId, val_Tipo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Proveedore_Articulo_ConsultarAsync(int val_EmpresaId, string val_ProveedorId, string val_ArticuloId, int val_Tipo) {
            return base.Channel.Proveedore_Articulo_ConsultarAsync(val_EmpresaId, val_ProveedorId, val_ArticuloId, val_Tipo);
        }
        
        public System.Data.DataTable Categorias_Consultar(string val_GrupoId01) {
            return base.Channel.Categorias_Consultar(val_GrupoId01);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Categorias_ConsultarAsync(string val_GrupoId01) {
            return base.Channel.Categorias_ConsultarAsync(val_GrupoId01);
        }
        
        public System.Data.DataTable Familias_Consultar(string val_GrupoId02) {
            return base.Channel.Familias_Consultar(val_GrupoId02);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Familias_ConsultarAsync(string val_GrupoId02) {
            return base.Channel.Familias_ConsultarAsync(val_GrupoId02);
        }
        
        public System.Data.DataTable SubFamilias_Consultar(string val_GrupoId03) {
            return base.Channel.SubFamilias_Consultar(val_GrupoId03);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SubFamilias_ConsultarAsync(string val_GrupoId03) {
            return base.Channel.SubFamilias_ConsultarAsync(val_GrupoId03);
        }
        
        public System.Data.DataTable UMedida_Consultar(string val_UMedidaId) {
            return base.Channel.UMedida_Consultar(val_UMedidaId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> UMedida_ConsultarAsync(string val_UMedidaId) {
            return base.Channel.UMedida_ConsultarAsync(val_UMedidaId);
        }
        
        public System.Data.DataTable Redondeo_Consultar(string val_cat_nemonico) {
            return base.Channel.Redondeo_Consultar(val_cat_nemonico);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Redondeo_ConsultarAsync(string val_cat_nemonico) {
            return base.Channel.Redondeo_ConsultarAsync(val_cat_nemonico);
        }
        
        public System.Data.DataTable Almacen_Consultar(int val_EmpresaId, int val_LocalId, int val_AlmacenId, int val_Tipo) {
            return base.Channel.Almacen_Consultar(val_EmpresaId, val_LocalId, val_AlmacenId, val_Tipo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Almacen_ConsultarAsync(int val_EmpresaId, int val_LocalId, int val_AlmacenId, int val_Tipo) {
            return base.Channel.Almacen_ConsultarAsync(val_EmpresaId, val_LocalId, val_AlmacenId, val_Tipo);
        }
        
        public System.Data.DataTable Estado_Proceso_WebService(int val_EmpresaId, int val_LocalId) {
            return base.Channel.Estado_Proceso_WebService(val_EmpresaId, val_LocalId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Estado_Proceso_WebServiceAsync(int val_EmpresaId, int val_LocalId) {
            return base.Channel.Estado_Proceso_WebServiceAsync(val_EmpresaId, val_LocalId);
        }
        
        public System.Data.DataTable Orden_Compra_Consultar(int val_EmpresaId, int val_LocalId, string val_NroPedido) {
            return base.Channel.Orden_Compra_Consultar(val_EmpresaId, val_LocalId, val_NroPedido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Orden_Compra_ConsultarAsync(int val_EmpresaId, int val_LocalId, string val_NroPedido) {
            return base.Channel.Orden_Compra_ConsultarAsync(val_EmpresaId, val_LocalId, val_NroPedido);
        }
        
        public System.Data.DataTable Orden_Compra_Detalle_Consultar(int val_EmpresaId, int val_LocalId, string val_NroPedido, int val_Item) {
            return base.Channel.Orden_Compra_Detalle_Consultar(val_EmpresaId, val_LocalId, val_NroPedido, val_Item);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Orden_Compra_Detalle_ConsultarAsync(int val_EmpresaId, int val_LocalId, string val_NroPedido, int val_Item) {
            return base.Channel.Orden_Compra_Detalle_ConsultarAsync(val_EmpresaId, val_LocalId, val_NroPedido, val_Item);
        }
        
        public System.Data.DataTable EasyTaxiCODESFile_Consulta(string val_value, string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento, string val_fecsistema, string val_hora, string val_cantidad) {
            return base.Channel.EasyTaxiCODESFile_Consulta(val_value, val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento, val_fecsistema, val_hora, val_cantidad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_ConsultaAsync(string val_value, string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento, string val_fecsistema, string val_hora, string val_cantidad) {
            return base.Channel.EasyTaxiCODESFile_ConsultaAsync(val_value, val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento, val_fecsistema, val_hora, val_cantidad);
        }
        
        public System.Data.DataTable EasyTaxiCODESFile_Consulta_Documento(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento) {
            return base.Channel.EasyTaxiCODESFile_Consulta_Documento(val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_Consulta_DocumentoAsync(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento) {
            return base.Channel.EasyTaxiCODESFile_Consulta_DocumentoAsync(val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento);
        }
        
        public System.Data.DataTable EasyTaxiCODESFile_Liberar(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento) {
            return base.Channel.EasyTaxiCODESFile_Liberar(val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_LiberarAsync(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento) {
            return base.Channel.EasyTaxiCODESFile_LiberarAsync(val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento);
        }
        
        public System.Data.DataTable EasyTaxiCODESFile_Anular(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento) {
            return base.Channel.EasyTaxiCODESFile_Anular(val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_AnularAsync(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento) {
            return base.Channel.EasyTaxiCODESFile_AnularAsync(val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento);
        }
        
        public System.Data.DataTable EasyTaxiCODESFile_Anexado(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento, string val_nroplaca) {
            return base.Channel.EasyTaxiCODESFile_Anexado(val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento, val_nroplaca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EasyTaxiCODESFile_AnexadoAsync(string val_localId, string val_nroseriemaq, string val_tipodocid, string val_nrodocumento, string val_nroplaca) {
            return base.Channel.EasyTaxiCODESFile_AnexadoAsync(val_localId, val_nroseriemaq, val_tipodocid, val_nrodocumento, val_nroplaca);
        }
        
        public System.Data.DataTable Clientes_Consultar(int val_EmpresaId, string val_ClienteId, int val_TipoCliente) {
            return base.Channel.Clientes_Consultar(val_EmpresaId, val_ClienteId, val_TipoCliente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Clientes_ConsultarAsync(int val_EmpresaId, string val_ClienteId, int val_TipoCliente) {
            return base.Channel.Clientes_ConsultarAsync(val_EmpresaId, val_ClienteId, val_TipoCliente);
        }
        
        public System.Data.DataTable LineaCredito_SaldoClid_Consultar() {
            return base.Channel.LineaCredito_SaldoClid_Consultar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LineaCredito_SaldoClid_ConsultarAsync() {
            return base.Channel.LineaCredito_SaldoClid_ConsultarAsync();
        }
        
        public System.Data.DataTable LineaCredito_SaldoClic_Consultar(int val_EmpresaId, int val_LocalId, string val_Cdcliente) {
            return base.Channel.LineaCredito_SaldoClic_Consultar(val_EmpresaId, val_LocalId, val_Cdcliente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LineaCredito_SaldoClic_ConsultarAsync(int val_EmpresaId, int val_LocalId, string val_Cdcliente) {
            return base.Channel.LineaCredito_SaldoClic_ConsultarAsync(val_EmpresaId, val_LocalId, val_Cdcliente);
        }
    }
}
