//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8937
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBCP.ServiceSIGES.Domain.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEParameters", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BEParameters : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string calculoigvField;
        
        private bool cambioturnoField;
        
        private string cdarticulocontableField;
        
        private string centralField;
        
        private string fe_act_clave_wsField;
        
        private string fe_act_ruta_wsField;
        
        private string fe_act_ruta_ws_CDRField;
        
        private string fe_act_rutaprocesamientoField;
        
        private string fe_asp_rutaprocesamientoField;
        
        private System.Nullable<int> fe_bzl_tiempoesperaField;
        
        private string fe_dbz_rutasuiteposField;
        
        private string fe_dbz_rutasuitesucField;
        
        private string fe_inc_rutaprocesamientoField;
        
        private string fe_ipremotoField;
        
        private string fe_mst_rutawebserviceField;
        
        private string fe_proveedorField;
        
        private string fe_puertoremotoField;
        
        private string fe_sge_clavecertificadoField;
        
        private string fe_sge_rutawebserviceField;
        
        private string fe_snt_rutafacturadorField;
        
        private string fe_snt_rutageneradorField;
        
        private string fe_snt_rutaprocesamientoField;
        
        private string fe_tci_rutaprocesamientoField;
        
        private bool flgdesgtkfactField;
        
        private bool flgmolotovField;
        
        private string idField;
        
        private string monpaisField;
        
        private string nom_ventaplayaField;
        
        private double numempresaField;
        
        private string path_bonusField;
        
        private string path_clicorpField;
        
        private string path_formatoField;
        
        private string path_gasboyField;
        
        private string path_loteriaField;
        
        private string path_repoField;
        
        private string path_transferField;
        
        private string tpanticipoField;
        
        private string tpaplicanticField;
        
        private string tpaplicncredField;
        
        private string tpboletaField;
        
        private string tpchequeField;
        
        private string tpcliente_corporativoField;
        
        private string tpcomandaField;
        
        private string tpfacturaField;
        
        private string tpguiaField;
        
        private string tpletraField;
        
        private string tpletraprotField;
        
        private string tpncreditoField;
        
        private string tpndebitoField;
        
        private string tpntavtaField;
        
        private string tppedidoField;
        
        private string tppgocanjeField;
        
        private string tppgochequeField;
        
        private string tppgocreditoField;
        
        private string tppgoefectivoField;
        
        private string tppgotarjetaField;
        
        private string tppgotransferenciaField;
        
        private string tpproformaField;
        
        private string tppromocionField;
        
        private string tpseparacionField;
        
        private string tpticketField;
        
        private string tpticketfacField;
        
        private string tpvaleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calculoigv
        {
            get
            {
                return this.calculoigvField;
            }
            set
            {
                this.calculoigvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool cambioturno
        {
            get
            {
                return this.cambioturnoField;
            }
            set
            {
                this.cambioturnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdarticulocontable
        {
            get
            {
                return this.cdarticulocontableField;
            }
            set
            {
                this.cdarticulocontableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string central
        {
            get
            {
                return this.centralField;
            }
            set
            {
                this.centralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_act_clave_ws
        {
            get
            {
                return this.fe_act_clave_wsField;
            }
            set
            {
                this.fe_act_clave_wsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_act_ruta_ws
        {
            get
            {
                return this.fe_act_ruta_wsField;
            }
            set
            {
                this.fe_act_ruta_wsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_act_ruta_ws_CDR
        {
            get
            {
                return this.fe_act_ruta_ws_CDRField;
            }
            set
            {
                this.fe_act_ruta_ws_CDRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_act_rutaprocesamiento
        {
            get
            {
                return this.fe_act_rutaprocesamientoField;
            }
            set
            {
                this.fe_act_rutaprocesamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_asp_rutaprocesamiento
        {
            get
            {
                return this.fe_asp_rutaprocesamientoField;
            }
            set
            {
                this.fe_asp_rutaprocesamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> fe_bzl_tiempoespera
        {
            get
            {
                return this.fe_bzl_tiempoesperaField;
            }
            set
            {
                this.fe_bzl_tiempoesperaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_dbz_rutasuitepos
        {
            get
            {
                return this.fe_dbz_rutasuiteposField;
            }
            set
            {
                this.fe_dbz_rutasuiteposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_dbz_rutasuitesuc
        {
            get
            {
                return this.fe_dbz_rutasuitesucField;
            }
            set
            {
                this.fe_dbz_rutasuitesucField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_inc_rutaprocesamiento
        {
            get
            {
                return this.fe_inc_rutaprocesamientoField;
            }
            set
            {
                this.fe_inc_rutaprocesamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_ipremoto
        {
            get
            {
                return this.fe_ipremotoField;
            }
            set
            {
                this.fe_ipremotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_mst_rutawebservice
        {
            get
            {
                return this.fe_mst_rutawebserviceField;
            }
            set
            {
                this.fe_mst_rutawebserviceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_proveedor
        {
            get
            {
                return this.fe_proveedorField;
            }
            set
            {
                this.fe_proveedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_puertoremoto
        {
            get
            {
                return this.fe_puertoremotoField;
            }
            set
            {
                this.fe_puertoremotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_sge_clavecertificado
        {
            get
            {
                return this.fe_sge_clavecertificadoField;
            }
            set
            {
                this.fe_sge_clavecertificadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_sge_rutawebservice
        {
            get
            {
                return this.fe_sge_rutawebserviceField;
            }
            set
            {
                this.fe_sge_rutawebserviceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_snt_rutafacturador
        {
            get
            {
                return this.fe_snt_rutafacturadorField;
            }
            set
            {
                this.fe_snt_rutafacturadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_snt_rutagenerador
        {
            get
            {
                return this.fe_snt_rutageneradorField;
            }
            set
            {
                this.fe_snt_rutageneradorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_snt_rutaprocesamiento
        {
            get
            {
                return this.fe_snt_rutaprocesamientoField;
            }
            set
            {
                this.fe_snt_rutaprocesamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fe_tci_rutaprocesamiento
        {
            get
            {
                return this.fe_tci_rutaprocesamientoField;
            }
            set
            {
                this.fe_tci_rutaprocesamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool flgdesgtkfact
        {
            get
            {
                return this.flgdesgtkfactField;
            }
            set
            {
                this.flgdesgtkfactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool flgmolotov
        {
            get
            {
                return this.flgmolotovField;
            }
            set
            {
                this.flgmolotovField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string monpais
        {
            get
            {
                return this.monpaisField;
            }
            set
            {
                this.monpaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_ventaplaya
        {
            get
            {
                return this.nom_ventaplayaField;
            }
            set
            {
                this.nom_ventaplayaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double numempresa
        {
            get
            {
                return this.numempresaField;
            }
            set
            {
                this.numempresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path_bonus
        {
            get
            {
                return this.path_bonusField;
            }
            set
            {
                this.path_bonusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path_clicorp
        {
            get
            {
                return this.path_clicorpField;
            }
            set
            {
                this.path_clicorpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path_formato
        {
            get
            {
                return this.path_formatoField;
            }
            set
            {
                this.path_formatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path_gasboy
        {
            get
            {
                return this.path_gasboyField;
            }
            set
            {
                this.path_gasboyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path_loteria
        {
            get
            {
                return this.path_loteriaField;
            }
            set
            {
                this.path_loteriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path_repo
        {
            get
            {
                return this.path_repoField;
            }
            set
            {
                this.path_repoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path_transfer
        {
            get
            {
                return this.path_transferField;
            }
            set
            {
                this.path_transferField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpanticipo
        {
            get
            {
                return this.tpanticipoField;
            }
            set
            {
                this.tpanticipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpaplicantic
        {
            get
            {
                return this.tpaplicanticField;
            }
            set
            {
                this.tpaplicanticField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpaplicncred
        {
            get
            {
                return this.tpaplicncredField;
            }
            set
            {
                this.tpaplicncredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpboleta
        {
            get
            {
                return this.tpboletaField;
            }
            set
            {
                this.tpboletaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpcheque
        {
            get
            {
                return this.tpchequeField;
            }
            set
            {
                this.tpchequeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpcliente_corporativo
        {
            get
            {
                return this.tpcliente_corporativoField;
            }
            set
            {
                this.tpcliente_corporativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpcomanda
        {
            get
            {
                return this.tpcomandaField;
            }
            set
            {
                this.tpcomandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpfactura
        {
            get
            {
                return this.tpfacturaField;
            }
            set
            {
                this.tpfacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpguia
        {
            get
            {
                return this.tpguiaField;
            }
            set
            {
                this.tpguiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpletra
        {
            get
            {
                return this.tpletraField;
            }
            set
            {
                this.tpletraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpletraprot
        {
            get
            {
                return this.tpletraprotField;
            }
            set
            {
                this.tpletraprotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpncredito
        {
            get
            {
                return this.tpncreditoField;
            }
            set
            {
                this.tpncreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpndebito
        {
            get
            {
                return this.tpndebitoField;
            }
            set
            {
                this.tpndebitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpntavta
        {
            get
            {
                return this.tpntavtaField;
            }
            set
            {
                this.tpntavtaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tppedido
        {
            get
            {
                return this.tppedidoField;
            }
            set
            {
                this.tppedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tppgocanje
        {
            get
            {
                return this.tppgocanjeField;
            }
            set
            {
                this.tppgocanjeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tppgocheque
        {
            get
            {
                return this.tppgochequeField;
            }
            set
            {
                this.tppgochequeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tppgocredito
        {
            get
            {
                return this.tppgocreditoField;
            }
            set
            {
                this.tppgocreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tppgoefectivo
        {
            get
            {
                return this.tppgoefectivoField;
            }
            set
            {
                this.tppgoefectivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tppgotarjeta
        {
            get
            {
                return this.tppgotarjetaField;
            }
            set
            {
                this.tppgotarjetaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tppgotransferencia
        {
            get
            {
                return this.tppgotransferenciaField;
            }
            set
            {
                this.tppgotransferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpproforma
        {
            get
            {
                return this.tpproformaField;
            }
            set
            {
                this.tpproformaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tppromocion
        {
            get
            {
                return this.tppromocionField;
            }
            set
            {
                this.tppromocionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpseparacion
        {
            get
            {
                return this.tpseparacionField;
            }
            set
            {
                this.tpseparacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpticket
        {
            get
            {
                return this.tpticketField;
            }
            set
            {
                this.tpticketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpticketfac
        {
            get
            {
                return this.tpticketfacField;
            }
            set
            {
                this.tpticketfacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpvale
        {
            get
            {
                return this.tpvaleField;
            }
            set
            {
                this.tpvaleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class Excepcion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string MensajeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="TS_SIParameters")]
public interface TS_SIParameters
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TS_SIParameters/SelTodoDetalle", ReplyAction="http://tempuri.org/TS_SIParameters/SelTodoDetalleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/TS_SIParameters/SelTodoDetalleExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEParameters SelTodoDetalle();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface TS_SIParametersChannel : TS_SIParameters, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TS_SIParametersClient : System.ServiceModel.ClientBase<TS_SIParameters>, TS_SIParameters
{
    
    public TS_SIParametersClient()
    {
    }
    
    public TS_SIParametersClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TS_SIParametersClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TS_SIParametersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TS_SIParametersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEParameters SelTodoDetalle()
    {
        return base.Channel.SelTodoDetalle();
    }
}
