//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.9148
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBCP.ServiceSIGES.Domain.Entities.Users
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BELogin", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BELogin : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ImeiField;
        
        private string SerieField;
        
        private string cdusuarioField;
        
        private string passwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imei
        {
            get
            {
                return this.ImeiField;
            }
            set
            {
                this.ImeiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie
        {
            get
            {
                return this.SerieField;
            }
            set
            {
                this.SerieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdusuario
        {
            get
            {
                return this.cdusuarioField;
            }
            set
            {
                this.cdusuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BELoginOutPut", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BELoginOutPut : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEEmpresaUser[] EmpresasField;
        
        private string JSONTokenField;
        
        private string MensajeField;
        
        private bool OkField;
        
        private int RetValField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEUsers UsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEEmpresaUser[] Empresas
        {
            get
            {
                return this.EmpresasField;
            }
            set
            {
                this.EmpresasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSONToken
        {
            get
            {
                return this.JSONTokenField;
            }
            set
            {
                this.JSONTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ok
        {
            get
            {
                return this.OkField;
            }
            set
            {
                this.OkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RetVal
        {
            get
            {
                return this.RetValField;
            }
            set
            {
                this.RetValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEUsers Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEEmpresaUser", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BEEmpresaUser : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdempresaField;
        
        private string cdnivelField;
        
        private string conexionField;
        
        private string drempresaField;
        
        private string dsempresaField;
        
        private string facturacion_electronicaField;
        
        private string rucempresaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdempresa
        {
            get
            {
                return this.cdempresaField;
            }
            set
            {
                this.cdempresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdnivel
        {
            get
            {
                return this.cdnivelField;
            }
            set
            {
                this.cdnivelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conexion
        {
            get
            {
                return this.conexionField;
            }
            set
            {
                this.conexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string drempresa
        {
            get
            {
                return this.drempresaField;
            }
            set
            {
                this.drempresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dsempresa
        {
            get
            {
                return this.dsempresaField;
            }
            set
            {
                this.dsempresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facturacion_electronica
        {
            get
            {
                return this.facturacion_electronicaField;
            }
            set
            {
                this.facturacion_electronicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rucempresa
        {
            get
            {
                return this.rucempresaField;
            }
            set
            {
                this.rucempresaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BELoginTurno", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BELoginTurno : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdempresaField;
        
        private string cdusuarioField;
        
        private string passwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdempresa
        {
            get
            {
                return this.cdempresaField;
            }
            set
            {
                this.cdempresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdusuario
        {
            get
            {
                return this.cdusuarioField;
            }
            set
            {
                this.cdusuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BELoginTurnoOutPut", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BELoginTurnoOutPut : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MensajeField;
        
        private bool OkField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ok
        {
            get
            {
                return this.OkField;
            }
            set
            {
                this.OkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEModulo", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BEModulo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdmoduloField;
        
        private string dsmoduloField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdmodulo
        {
            get
            {
                return this.cdmoduloField;
            }
            set
            {
                this.cdmoduloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dsmodulo
        {
            get
            {
                return this.dsmoduloField;
            }
            set
            {
                this.dsmoduloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BENivel", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BENivel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdempresaField;
        
        private string cdnivelField;
        
        private string codigoField;
        
        private string tipoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdempresa
        {
            get
            {
                return this.cdempresaField;
            }
            set
            {
                this.cdempresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdnivel
        {
            get
            {
                return this.cdnivelField;
            }
            set
            {
                this.cdnivelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEAccesos", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BEAccesos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdmoduloField;
        
        private string cdnivelField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdmodulo
        {
            get
            {
                return this.cdmoduloField;
            }
            set
            {
                this.cdmoduloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdnivel
        {
            get
            {
                return this.cdnivelField;
            }
            set
            {
                this.cdnivelField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITS_SIAutentication")]
public interface ITS_SIAutentication
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIAutentication/Login", ReplyAction="http://tempuri.org/ITS_SIAutentication/LoginResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIAutentication/LoginExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginOutPut Login(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELogin input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIAutentication/LoginTurno", ReplyAction="http://tempuri.org/ITS_SIAutentication/LoginTurnoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIAutentication/LoginTurnoExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginTurnoOutPut LoginTurno(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginTurno input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIAutentication/GetEmpresaUser", ReplyAction="http://tempuri.org/ITS_SIAutentication/GetEmpresaUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIAutentication/GetEmpresaUserExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEEmpresaUser[] GetEmpresaUser(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELogin input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIAutentication/GetModulos", ReplyAction="http://tempuri.org/ITS_SIAutentication/GetModulosResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIAutentication/GetModulosExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEModulo[] GetModulos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIAutentication/GetNivel", ReplyAction="http://tempuri.org/ITS_SIAutentication/GetNivelResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIAutentication/GetNivelExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BENivel[] GetNivel(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BENivel input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIAutentication/GetAccesos", ReplyAction="http://tempuri.org/ITS_SIAutentication/GetAccesosResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIAutentication/GetAccesosExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEAccesos[] GetAccesos(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEAccesos input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIAutentication/AuthorizeTerminal", ReplyAction="http://tempuri.org/ITS_SIAutentication/AuthorizeTerminalResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIAutentication/AuthorizeTerminalExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BETerminal AuthorizeTerminal(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELogin input);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITS_SIAutenticationChannel : ITS_SIAutentication, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TS_SIAutenticationClient : System.ServiceModel.ClientBase<ITS_SIAutentication>, ITS_SIAutentication
{
    
    public TS_SIAutenticationClient()
    {
    }
    
    public TS_SIAutenticationClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TS_SIAutenticationClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TS_SIAutenticationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TS_SIAutenticationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginOutPut Login(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELogin input)
    {
        return base.Channel.Login(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginTurnoOutPut LoginTurno(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginTurno input)
    {
        return base.Channel.LoginTurno(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEEmpresaUser[] GetEmpresaUser(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELogin input)
    {
        return base.Channel.GetEmpresaUser(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEModulo[] GetModulos()
    {
        return base.Channel.GetModulos();
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BENivel[] GetNivel(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BENivel input)
    {
        return base.Channel.GetNivel(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEAccesos[] GetAccesos(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BEAccesos input)
    {
        return base.Channel.GetAccesos(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BETerminal AuthorizeTerminal(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELogin input)
    {
        return base.Channel.AuthorizeTerminal(input);
    }
}
