//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.9148
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBCP.ServiceSIGES.Domain.Entities.Reimpresion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEVentagInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Reimpr" +
        "esion")]
    public partial class TS_BEVentagInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdtipodocField;
        
        private string nrodocumentoField;
        
        private string nroposField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdtipodoc
        {
            get
            {
                return this.cdtipodocField;
            }
            set
            {
                this.cdtipodocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrodocumento
        {
            get
            {
                return this.nrodocumentoField;
            }
            set
            {
                this.nrodocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEReimpresionLOutput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Reimpr" +
        "esion")]
    public partial class TS_BEReimpresionLOutput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEReimpresionL[] DocumentosField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje MensajeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEReimpresionL[] Documentos
        {
            get
            {
                return this.DocumentosField;
            }
            set
            {
                this.DocumentosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEReimpresionL", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Reimpr" +
        "esion")]
    public partial class TS_BEReimpresionL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool anuladoField;
        
        private string cdclienteField;
        
        private string cdtipodocField;
        
        private string estadoField;
        
        private System.DateTime fecdocumentoField;
        
        private string fechaField;
        
        private string nrodocumentoField;
        
        private string nroposField;
        
        private string nroseriemaqField;
        
        private string rsclienteField;
        
        private string tipodocField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool anulado
        {
            get
            {
                return this.anuladoField;
            }
            set
            {
                this.anuladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdcliente
        {
            get
            {
                return this.cdclienteField;
            }
            set
            {
                this.cdclienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdtipodoc
        {
            get
            {
                return this.cdtipodocField;
            }
            set
            {
                this.cdtipodocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecdocumento
        {
            get
            {
                return this.fecdocumentoField;
            }
            set
            {
                this.fecdocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrodocumento
        {
            get
            {
                return this.nrodocumentoField;
            }
            set
            {
                this.nrodocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroseriemaq
        {
            get
            {
                return this.nroseriemaqField;
            }
            set
            {
                this.nroseriemaqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rscliente
        {
            get
            {
                return this.rsclienteField;
            }
            set
            {
                this.rsclienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipodoc
        {
            get
            {
                return this.tipodocField;
            }
            set
            {
                this.tipodocField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEDocumentoInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Reimpr" +
        "esion")]
    public partial class TS_BEDocumentoInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdtipodocField;
        
        private string fechaField;
        
        private bool imprimirField;
        
        private string nrodocumentoField;
        
        private string nroposField;
        
        private string nroseriemaqField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cdtipodoc
        {
            get
            {
                return this.cdtipodocField;
            }
            set
            {
                this.cdtipodocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool imprimir
        {
            get
            {
                return this.imprimirField;
            }
            set
            {
                this.imprimirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nrodocumento
        {
            get
            {
                return this.nrodocumentoField;
            }
            set
            {
                this.nrodocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nroseriemaq
        {
            get
            {
                return this.nroseriemaqField;
            }
            set
            {
                this.nroseriemaqField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEUltimoDocumentoInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Reimpr" +
        "esion")]
    public partial class TS_BEUltimoDocumentoInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool imprimirField;
        
        private string nroposField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool imprimir
        {
            get
            {
                return this.imprimirField;
            }
            set
            {
                this.imprimirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEReimpresionLInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Reimpr" +
        "esion")]
    public partial class TS_BEReimpresionLInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdtipodocField;
        
        private string nrodocumentoField;
        
        private string nroposField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdtipodoc
        {
            get
            {
                return this.cdtipodocField;
            }
            set
            {
                this.cdtipodocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrodocumento
        {
            get
            {
                return this.nrodocumentoField;
            }
            set
            {
                this.nrodocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
    }
}
namespace ITBCP.ServiceSIGES.Domain.Entities
{
    using System.Runtime.Serialization;

    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BERespuesta", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BERespuesta : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string base64encodehtmlField;
        
        private string base64encodepdfField;
        
        private bool okField;
        
        private string respuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string base64encodehtml
        {
            get
            {
                return this.base64encodehtmlField;
            }
            set
            {
                this.base64encodehtmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string base64encodepdf
        {
            get
            {
                return this.base64encodepdfField;
            }
            set
            {
                this.base64encodepdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ok
        {
            get
            {
                return this.okField;
            }
            set
            {
                this.okField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEInicioDiaOutput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BEInicioDiaOutput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje MensajeField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.TS_BETerminal vTerminalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.TS_BETerminal vTerminal
        {
            get
            {
                return this.vTerminalField;
            }
            set
            {
                this.vTerminalField = value;
            }
        }
    }
   
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEDepositoInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BEDepositoInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdtppagoField;
        
        private string cdvendedorField;
        
        private string dsvendedorField;
        
        private decimal mtodolaresField;
        
        private decimal mtosolesField;
        
        private string nroposField;
        
        private int nrosobresField;
        
        private bool turno_anteriorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdtppago
        {
            get
            {
                return this.cdtppagoField;
            }
            set
            {
                this.cdtppagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdvendedor
        {
            get
            {
                return this.cdvendedorField;
            }
            set
            {
                this.cdvendedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dsvendedor
        {
            get
            {
                return this.dsvendedorField;
            }
            set
            {
                this.dsvendedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal mtodolares
        {
            get
            {
                return this.mtodolaresField;
            }
            set
            {
                this.mtodolaresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal mtosoles
        {
            get
            {
                return this.mtosolesField;
            }
            set
            {
                this.mtosolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nrosobres
        {
            get
            {
                return this.nrosobresField;
            }
            set
            {
                this.nrosobresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool turno_anterior
        {
            get
            {
                return this.turno_anteriorField;
            }
            set
            {
                this.turno_anteriorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEDepositos", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BEDepositos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.TS_BEDeposito[] cDepositosField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje cMensajeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.TS_BEDeposito[] cDepositos
        {
            get
            {
                return this.cDepositosField;
            }
            set
            {
                this.cDepositosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje cMensaje
        {
            get
            {
                return this.cMensajeField;
            }
            set
            {
                this.cMensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEDeposito", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BEDeposito : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.TS_BEFormato cFormatoField;
        
        private string cdtppagoField;
        
        private string cdvendedorField;
        
        private string dstppagoField;
        
        private string dsvendedorField;
        
        private System.DateTime fecdocumentoField;
        
        private string fechaField;
        
        private string infoField;
        
        private decimal mtodolaresField;
        
        private decimal mtosolesField;
        
        private string nrodepositoField;
        
        private string nrodocumentoField;
        
        private string nroposField;
        
        private string nroseriemaqField;
        
        private int nrosobresField;
        
        private int turnoField;
        
        private bool turno_anteriorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.TS_BEFormato cFormato
        {
            get
            {
                return this.cFormatoField;
            }
            set
            {
                this.cFormatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdtppago
        {
            get
            {
                return this.cdtppagoField;
            }
            set
            {
                this.cdtppagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdvendedor
        {
            get
            {
                return this.cdvendedorField;
            }
            set
            {
                this.cdvendedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dstppago
        {
            get
            {
                return this.dstppagoField;
            }
            set
            {
                this.dstppagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dsvendedor
        {
            get
            {
                return this.dsvendedorField;
            }
            set
            {
                this.dsvendedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecdocumento
        {
            get
            {
                return this.fecdocumentoField;
            }
            set
            {
                this.fecdocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal mtodolares
        {
            get
            {
                return this.mtodolaresField;
            }
            set
            {
                this.mtodolaresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal mtosoles
        {
            get
            {
                return this.mtosolesField;
            }
            set
            {
                this.mtosolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrodeposito
        {
            get
            {
                return this.nrodepositoField;
            }
            set
            {
                this.nrodepositoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrodocumento
        {
            get
            {
                return this.nrodocumentoField;
            }
            set
            {
                this.nrodocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroseriemaq
        {
            get
            {
                return this.nroseriemaqField;
            }
            set
            {
                this.nroseriemaqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nrosobres
        {
            get
            {
                return this.nrosobresField;
            }
            set
            {
                this.nrosobresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int turno
        {
            get
            {
                return this.turnoField;
            }
            set
            {
                this.turnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool turno_anterior
        {
            get
            {
                return this.turno_anteriorField;
            }
            set
            {
                this.turno_anteriorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEFormato", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BEFormato : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string footerField;
        
        private string headerField;
        
        private decimal puntos_canjeadosField;
        
        private decimal valor_canjeadosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string footer
        {
            get
            {
                return this.footerField;
            }
            set
            {
                this.footerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal puntos_canjeados
        {
            get
            {
                return this.puntos_canjeadosField;
            }
            set
            {
                this.puntos_canjeadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valor_canjeados
        {
            get
            {
                return this.valor_canjeadosField;
            }
            set
            {
                this.valor_canjeadosField = value;
            }
        }
    }
   
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BELadoEInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BELadoEInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ladoField;
        
        private string nroposField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lado
        {
            get
            {
                return this.ladoField;
            }
            set
            {
                this.ladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEDepositoEInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BEDepositoEInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime fecprocesoField;
        
        private string nrodepositoField;
        
        private string nroposField;
        
        private string turnoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecproceso
        {
            get
            {
                return this.fecprocesoField;
            }
            set
            {
                this.fecprocesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrodeposito
        {
            get
            {
                return this.nrodepositoField;
            }
            set
            {
                this.nrodepositoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string turno
        {
            get
            {
                return this.turnoField;
            }
            set
            {
                this.turnoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEVendedores", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    public partial class TS_BEVendedores : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje MensajeField;
        
        private ITBCP.ServiceSIGES.Domain.Entities.TS_BEVendedor[] cVendedoresField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ITBCP.ServiceSIGES.Domain.Entities.TS_BEVendedor[] cVendedores
        {
            get
            {
                return this.cVendedoresField;
            }
            set
            {
                this.cVendedoresField = value;
            }
        }
    }

}
namespace ITBCP.ServiceSIGES.Domain.Entities.Cierrres
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEXCierreInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Cierrr" +
        "es")]
    public partial class TS_BEXCierreInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string dsusuarioField;
        
        private bool ignorar_bloqueo_playaField;
        
        private bool imprimirField;
        
        private string nroposField;
        
        private string usuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string dsusuario
        {
            get
            {
                return this.dsusuarioField;
            }
            set
            {
                this.dsusuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ignorar_bloqueo_playa
        {
            get
            {
                return this.ignorar_bloqueo_playaField;
            }
            set
            {
                this.ignorar_bloqueo_playaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool imprimir
        {
            get
            {
                return this.imprimirField;
            }
            set
            {
                this.imprimirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BEZCierreInput", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Cierrr" +
        "es")]
    public partial class TS_BEZCierreInput : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ignorar_bloqueo_playaField;
        
        private bool imprimirField;
        
        private string nroposField;
        
        private string usuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ignorar_bloqueo_playa
        {
            get
            {
                return this.ignorar_bloqueo_playaField;
            }
            set
            {
                this.ignorar_bloqueo_playaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool imprimir
        {
            get
            {
                return this.imprimirField;
            }
            set
            {
                this.imprimirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nropos
        {
            get
            {
                return this.nroposField;
            }
            set
            {
                this.nroposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
}
namespace ITBCP.ServiceSIGES.Domain.Entities.Users
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TS_BELoginVendedor", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities.Users")]
    public partial class TS_BELoginVendedor : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdempresaField;
        
        private string claveField;
        
        private string usuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdempresa
        {
            get
            {
                return this.cdempresaField;
            }
            set
            {
                this.cdempresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITS_SIImpresion")]
public interface ITS_SIImpresion
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_DOCUMENTO_IMPRESO_VENTAG", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_DOCUMENTO_IMPRESO_VENTAGResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_DOCUMENTO_IMPRESO_VENTAGExcepcionFault" +
        "", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEReimpresionLOutput OBTENER_DOCUMENTO_IMPRESO_VENTAG(ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEVentagInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_DOCUMENTO_IMPRESO", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_DOCUMENTO_IMPRESOResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_DOCUMENTO_IMPRESOExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje OBTENER_DOCUMENTO_IMPRESO(ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEDocumentoInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_ULTIMO_DOCUMENTO_IMPRESO", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_ULTIMO_DOCUMENTO_IMPRESOResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_ULTIMO_DOCUMENTO_IMPRESOExcepcionFault" +
        "", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje OBTENER_ULTIMO_DOCUMENTO_IMPRESO(ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEUltimoDocumentoInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_CIERRE_X", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_CIERRE_XResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_CIERRE_XExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BERespuesta OBTENER_CIERRE_X(ITBCP.ServiceSIGES.Domain.Entities.Cierrres.TS_BEXCierreInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_CIERRE_Z", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_CIERRE_ZResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_CIERRE_ZExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BERespuesta OBTENER_CIERRE_Z(ITBCP.ServiceSIGES.Domain.Entities.Cierrres.TS_BEZCierreInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_CAMBIO_TURNO", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_CAMBIO_TURNOResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_CAMBIO_TURNOExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje OBTENER_CAMBIO_TURNO(bool Enviar, bool OmitirBloqueoPlaya);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_INICIO_DIA", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_INICIO_DIAResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_INICIO_DIAExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEInicioDiaOutput OBTENER_INICIO_DIA(string seriehd, string cdusuario);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/REGISTRAR_DEPOSITO", ReplyAction="http://tempuri.org/ITS_SIImpresion/REGISTRAR_DEPOSITOResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/REGISTRAR_DEPOSITOExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje REGISTRAR_DEPOSITO(ITBCP.ServiceSIGES.Domain.Entities.TS_BEDepositoInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/CONSULTAR_DEPOSITOS", ReplyAction="http://tempuri.org/ITS_SIImpresion/CONSULTAR_DEPOSITOSResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/CONSULTAR_DEPOSITOSExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEDepositos CONSULTAR_DEPOSITOS(string nropos, string cdvendedor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_DEPOSITO_GRIFERO", ReplyAction="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_DEPOSITO_GRIFEROResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_DEPOSITO_GRIFEROExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje AUTENTICAR_DEPOSITO_GRIFERO(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginVendedor input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/REGISTRAR_GRIFERO_LADOS", ReplyAction="http://tempuri.org/ITS_SIImpresion/REGISTRAR_GRIFERO_LADOSResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/REGISTRAR_GRIFERO_LADOSExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje REGISTRAR_GRIFERO_LADOS(ITBCP.ServiceSIGES.Domain.Entities.TS_BELado input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_GRIFERO_LADOS", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_GRIFERO_LADOSResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_GRIFERO_LADOSExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BELados OBTENER_GRIFERO_LADOS(string nropos);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/ELIMINAR_GRIFERO_LADOS", ReplyAction="http://tempuri.org/ITS_SIImpresion/ELIMINAR_GRIFERO_LADOSResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/ELIMINAR_GRIFERO_LADOSExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje ELIMINAR_GRIFERO_LADOS(ITBCP.ServiceSIGES.Domain.Entities.TS_BELadoEInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/ELIMINAR_DEPOSITO", ReplyAction="http://tempuri.org/ITS_SIImpresion/ELIMINAR_DEPOSITOResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/ELIMINAR_DEPOSITOExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje ELIMINAR_DEPOSITO(ITBCP.ServiceSIGES.Domain.Entities.TS_BEDepositoEInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_VENDEDORES", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_VENDEDORESResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_VENDEDORESExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEVendedores OBTENER_VENDEDORES(string cdempresa);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_GRIFERO_LADOS", ReplyAction="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_GRIFERO_LADOSResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_GRIFERO_LADOSExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje AUTENTICAR_GRIFERO_LADOS(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginVendedor input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_CONFIGURACION_LADOS", ReplyAction="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_CONFIGURACION_LADOSResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/AUTENTICAR_CONFIGURACION_LADOSExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje AUTENTICAR_CONFIGURACION_LADOS(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginVendedor input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/LISTAR_DOCUMENTOS_REIMPRESION", ReplyAction="http://tempuri.org/ITS_SIImpresion/LISTAR_DOCUMENTOS_REIMPRESIONResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/LISTAR_DOCUMENTOS_REIMPRESIONExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEReimpresionLOutput LISTAR_DOCUMENTOS_REIMPRESION(ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEReimpresionLInput input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITS_SIImpresion/OBTENER_VENTAS_PENDIENTES_POR_TERMINAL_SEMI_AU" +
        "TOMATIC", ReplyAction="http://tempuri.org/ITS_SIImpresion/OBTENER_VENTAS_PENDIENTES_POR_TERMINAL_SEMI_AU" +
        "TOMATICResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITBCP.ServiceSIGES.Domain.Entities.Excepcion), Action="http://tempuri.org/ITS_SIImpresion/OBTENER_VENTAS_PENDIENTES_POR_TERMINAL_SEMI_AU" +
        "TOMATICExcepcionFault", Name="Excepcion", Namespace="http://schemas.datacontract.org/2004/07/ITBCP.ServiceSIGES.Domain.Entities")]
    bool OBTENER_VENTAS_PENDIENTES_POR_TERMINAL_SEMI_AUTOMATIC(string nropos);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITS_SIImpresionChannel : ITS_SIImpresion, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TS_SIImpresionClient : System.ServiceModel.ClientBase<ITS_SIImpresion>, ITS_SIImpresion
{
    
    public TS_SIImpresionClient()
    {
    }
    
    public TS_SIImpresionClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TS_SIImpresionClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TS_SIImpresionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TS_SIImpresionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEReimpresionLOutput OBTENER_DOCUMENTO_IMPRESO_VENTAG(ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEVentagInput input)
    {
        return base.Channel.OBTENER_DOCUMENTO_IMPRESO_VENTAG(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje OBTENER_DOCUMENTO_IMPRESO(ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEDocumentoInput input)
    {
        return base.Channel.OBTENER_DOCUMENTO_IMPRESO(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje OBTENER_ULTIMO_DOCUMENTO_IMPRESO(ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEUltimoDocumentoInput input)
    {
        return base.Channel.OBTENER_ULTIMO_DOCUMENTO_IMPRESO(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BERespuesta OBTENER_CIERRE_X(ITBCP.ServiceSIGES.Domain.Entities.Cierrres.TS_BEXCierreInput input)
    {
        return base.Channel.OBTENER_CIERRE_X(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BERespuesta OBTENER_CIERRE_Z(ITBCP.ServiceSIGES.Domain.Entities.Cierrres.TS_BEZCierreInput input)
    {
        return base.Channel.OBTENER_CIERRE_Z(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje OBTENER_CAMBIO_TURNO(bool Enviar, bool OmitirBloqueoPlaya)
    {
        return base.Channel.OBTENER_CAMBIO_TURNO(Enviar, OmitirBloqueoPlaya);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEInicioDiaOutput OBTENER_INICIO_DIA(string seriehd, string cdusuario)
    {
        return base.Channel.OBTENER_INICIO_DIA(seriehd, cdusuario);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje REGISTRAR_DEPOSITO(ITBCP.ServiceSIGES.Domain.Entities.TS_BEDepositoInput input)
    {
        return base.Channel.REGISTRAR_DEPOSITO(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEDepositos CONSULTAR_DEPOSITOS(string nropos, string cdvendedor)
    {
        return base.Channel.CONSULTAR_DEPOSITOS(nropos, cdvendedor);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje AUTENTICAR_DEPOSITO_GRIFERO(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginVendedor input)
    {
        return base.Channel.AUTENTICAR_DEPOSITO_GRIFERO(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje REGISTRAR_GRIFERO_LADOS(ITBCP.ServiceSIGES.Domain.Entities.TS_BELado input)
    {
        return base.Channel.REGISTRAR_GRIFERO_LADOS(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BELados OBTENER_GRIFERO_LADOS(string nropos)
    {
        return base.Channel.OBTENER_GRIFERO_LADOS(nropos);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje ELIMINAR_GRIFERO_LADOS(ITBCP.ServiceSIGES.Domain.Entities.TS_BELadoEInput input)
    {
        return base.Channel.ELIMINAR_GRIFERO_LADOS(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje ELIMINAR_DEPOSITO(ITBCP.ServiceSIGES.Domain.Entities.TS_BEDepositoEInput input)
    {
        return base.Channel.ELIMINAR_DEPOSITO(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEVendedores OBTENER_VENDEDORES(string cdempresa)
    {
        return base.Channel.OBTENER_VENDEDORES(cdempresa);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje AUTENTICAR_GRIFERO_LADOS(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginVendedor input)
    {
        return base.Channel.AUTENTICAR_GRIFERO_LADOS(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.TS_BEMensaje AUTENTICAR_CONFIGURACION_LADOS(ITBCP.ServiceSIGES.Domain.Entities.Users.TS_BELoginVendedor input)
    {
        return base.Channel.AUTENTICAR_CONFIGURACION_LADOS(input);
    }
    
    public ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEReimpresionLOutput LISTAR_DOCUMENTOS_REIMPRESION(ITBCP.ServiceSIGES.Domain.Entities.Reimpresion.TS_BEReimpresionLInput input)
    {
        return base.Channel.LISTAR_DOCUMENTOS_REIMPRESION(input);
    }
    
    public bool OBTENER_VENTAS_PENDIENTES_POR_TERMINAL_SEMI_AUTOMATIC(string nropos)
    {
        return base.Channel.OBTENER_VENTAS_PENDIENTES_POR_TERMINAL_SEMI_AUTOMATIC(nropos);
    }
}
